name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v19
    secrets:
      nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
    with:
      filter_builds: .top_attr
